baseURL = 'https://hambungle.com/'
languageCode = 'en-us'
title = 'Hambungle'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false

[languages]
  [languages.en]
    languageName = 'English'
    languageCode = 'en-US'
    languageDirection = 'ltr'
    weight = 1
  [languages.ar]
    languageName = 'العربية'
    languageCode = 'ar'
    languageDirection = 'rtl'
    weight = 2
  [languages.es]
    languageName = 'Español'
    languageCode = 'es'
    languageDirection = 'ltr'
    weight = 3
  [languages.hi]
    languageName = 'हिन्दी'
    languageCode = 'hi'
    languageDirection = 'ltr'
    weight = 4
  [languages.zh]
    languageName = '中文'
    languageCode = 'zh'
    languageDirection = 'ltr'
    weight = 5
